# Site
repository: XiaoTailong/Shaw
favicon: images/favicon.ico

# Personal info
name: 肖太龙
title: 上海交通大学博士生在读
email: tailong_shaw@sjtu.edu.cn
phone: +86 18601736021
# website: https://xiaotailong.github.io/Shaw/
QQ: 2449734455
# Social links
github_username:  XiaoTailong

linkedin_username: Tailong Xiao

# pinterest_username: jekyll
# youtube_username: globalmtb
additional_links:
- title: zhihu
  icon: fa-zhihu (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://www.zhihu.com/people/xiao-tai-long-16
- title: google
  icon: fa-google
  url: https://scholar.google.com/citations?user=qo67_eUAAAAJ&hl=en



# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  - 本人来自湖北省孝感市，现就读于上海交通大学电子信息与电气工程学院电子系信息与通信工程专业。
  目前处于物理与计算机科学的交叉领域，致力于将量子力学原理应用于计算机科学，主要是机器学习领域。
  - 编程语言: python, C/C++, Matlab, Latex, Markdown, Mathmatica, SQL, etc.
  - 机器学习框架：pytorch, tesorflow-quantum, qutip, Cirq, etc. 
  - 工作技能：能快速了解新领域的知识，具有良好的<mark>数学基础</mark>，具有一定的<mark>创新能力</mark>，擅长<mark>团队合作</mark>。

# Research Interests Section
# projects_title: Research Interests

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  - 本人兴趣爱好广泛但都不深入，没有值得称道的特长。如果说大部分的时间都在干的事情，那就是
  <mark>看文献</mark>、<mark>做笔记</mark>、<mark>看小说</mark>、<mark>打游戏(刺激战场和王者荣耀)</mark>。
  比较喜欢的书籍有《活着》，《平凡的世界》，《红与黑》，《大清相国》，《资本论》等。
  - 本人不擅旅游，对于很多户外活动不心动，但是非常注重<mark>健身</mark>和<mark>跑步</mark>。对于乒乓球和篮球等球类运动不抵触，都会积极参与。
  - 本人不爱美食。

# Footer
footer_show_references: true

# Build settings
remote_theme: XiaoTailong/Shaw

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
